# Generated by Django 3.0.3 on 2020-03-05 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('ac_type', models.CharField(choices=[('Ind', 'Individual'), ('Org', 'Organization')], max_length=3)),
                ('job_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to='portfolio.UserProfile')),
                ('following', models.ManyToManyField(blank=True, related_name='following_profile', to='portfolio.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Address', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.UserProfile')),
            ],
        ),
    ]
